services:
  webapp:
    build: .
    image: idk2003/webfortest:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=hospitaldb1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Ych@1805909590
  db:
    image: idk2003/mysqlfortest:latest
    environment:
      MYSQL_ROOT_PASSWORD: Ych@1805909590
      MYSQL_DATABASE: hospitaldb1
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: